import type { Metadata } from "next";
import {Barlow_Semi_Condensed, Enriqueta} from "next/font/google";
import "./globals.css";
import Header from "./_components/layout/Header";
import Footer from "./_components/layout/Footer";


const barlowSemi = Barlow_Semi_Condensed({
  weight: "400",
  variable: "--font-barlow-semi",
  subsets: ["latin"],
});

const enriqueta = Enriqueta({
  weight: "400",
  variable: "--font-enriqueta",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "aben",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`flex flex-col h-screen ${barlowSemi.variable} ${enriqueta.variable} font-main bg-[var(--white)]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
