import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Barlow_Semi_Condensed} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/layout/Navbar";
import Footer from "./_components/layout/Footer";


const barlowSemi = Barlow_Semi_Condensed({
  weight: "400",
  variable: "--font-barlow-semi",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "aben",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${barlowSemi.className} ${barlowSemi.variable} bg-[var(--white)]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
